@startuml

'skin rose

'This can hide the boxes at the bottom
hide footbox

actor Client as Client
participant Chirp.Web as Web
participant Chirp.Core as Core
participant Chirp.Infrastructure as Infrastructure
database Database as Database

'Redirects from / to /?page=1
Client -> Web ++ : HTTPS GET Request: /
return HTTPS Response: 302 Found

||||

Client -> Web ++ : HTTPS GET Request: /?page=1 .

'Get amount of pages for pagebuttons
  Web -> Core ++ : CheepService.GetAmountOfCheepPages(pageSize)  .
    Core -> Infrastructure ++ : GetAmountOfCheeps()
      Infrastructure -> Database ++ : SQLite Query
      return AmountOfCheeps
    return Task<int> amountOfCheeps
  return int amountOfCheepPages

||||

'Get cheeps from current page
  Web -> Core ++ : CheepService.GetCheepsByPage(page, pageSize)
    Core -> Infrastructure ++ : GetCheepsByPage(page, pageSize)
      Infrastructure -> Database ++ : SQLite Query
      return Cheeps
    return Task<IEnumerable<CheepDTO>> cheeps
  return IEnumerable<CheepDTO> cheeps

||||

'Extract authors from cheeps
Web -> Web : Extract author names from cheeps

'Get authors to get profile images 
  Web -> Core ++ : AuthorService.GetAuthorsByNames(names)
    Core -> Infrastructure ++ : GetAuthorsByNames(names)
      Infrastructure -> Database ++ : SQLite Query
      return Authors
    return Task<IEnumerable<AuthorDTO>> authors
  return IEnumerable<AuthorDTO> authors

return HTTPS Response: 200

@enduml