#This aumtomaticly release when a pul request to main is accepted
name: Release on PR Merge
permissions: write-all

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 #Fetch all history and tags

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore Chirp/
      
      - name: Build
        run: dotnet build --no-restore Chirp/
      
      - name: Test
        run: dotnet test --no-build --verbosity normal Chirp/

       # Get the latest tag from the repository
      - name: Get latest tag
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 || echo "v0.0.0")  # Get latest tag or default to v0.0.0
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          echo "Current latest tag is $LATEST_TAG"
      
      - name: release for all platforms
        working-directory: Chirp/src/Chirp.Razor/
        run: |
          dotnet publish --runtime linux-x64 -p:PublishSingleFile=true --self-contained true
          dotnet publish --runtime win-x64 -p:PublishSingleFile=true --self-contained true
          dotnet publish --runtime osx-x64 -p:PublishSingleFile=true --self-contained true
          
      # Create ZIP files
      - name: Zip the output
        working-directory: Chirp/src/Chirp.Razor/bin/Release/net8.0/
        run: |
          cd publish/linux-x64
          zip -r chirp-${{ env.NEW_VERSION }}-linux-x64.zip Chirp
          cd ../win-x64
          zip -r chirp-${{ env.NEW_VERSION }}-win-x64.zip Chirp
          cd ../osx-x64
          zip -r chirp-${{ env.NEW_VERSION }}-osx-x64.zip Chirp


      # Upload the release artifacts and create the release
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.NEW_VERSION }}  # Use the new version tag
          name: Release ${{ env.NEW_VERSION }}  # Set release name
          files: |
            Chirp/src/Chirp.Razor/bin/Release/net8.0/Chirp/publish/linux-x64/chirp-${{ env.NEW_VERSION }}-linux-x64.zip
            Chirp/src/Chirp.Razor/bin/Release/net8.0/Chirp/publish/win-x64/chirp-${{ env.NEW_VERSION }}-win-x64.zip
            Chirp/src/Chirp.Razor/bin/Release/net8.0/Chirp/publish/osx-x64/chirp-${{ env.NEW_VERSION }}-osx-x64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
