#Adapted from 
#https://github.com/marketplace/actions/post-warnings-errors-as-pr-comment#workflow-example

name: Check for warnings

on: [pull_request]

jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - name: Post PR comment for warnings/errors
      if: always()
      uses: JacobDomagala/CompileResult@master
      with:
        comment_title: WARNINGS AND ERRORS
        compile_result_file: ${{runner.workspace}}/build/output.txt
