#Adapted from 
#https://github.com/marketplace/actions/post-warnings-errors-as-pr-comment#workflow-example
#In colabriation with, chat-gpt

name: Check for warnings

on: [pull_request]

jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - name: setup Build Directory
      shell: bash
      run: mkdir -p ${{runner.workspace}}/build
    
    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: |
        dotnet build $GITHUB_WORKSPACE --output ${{runner.workspace}}/build 2> >(tee "output.txt")

    
    - name: Post PR comment for warnings/errors
      if: always()
      uses: JacobDomagala/CompileResult@master
      with:
        comment_title: WARNINGS AND ERRORS
        compile_result_file: ${{runner.workspace}}/build/output.txt
